### ISSUE TITLE
严重Bug，设定的点击文字有换行的话，换行前的文字都不能点击

### ISSUE THREAD

**Issue by zhaobb88** [lyb5834/YBAttributeTextTapAction#15]
严重Bug，设定的点击文字有换行的话，设定的换行前的文字都不能点击

**Comment by zhaobb88** [comment]
哦 我发现设置NSMutableParagraphStyle这个为NSLineBreakByCharWrapping就好了

**Comment by CoderEzilWang** [comment]
我也发现这个问题,楼上的解决方法有效

**Comment by lyb5834** [comment]
最好使用最新的3.0.0版本，点击准确率大大提升

**Comment by JerryMR** [comment]
这样操作就没有...了  有没有办法让支持NSLineBreakByTruncatingTail @lyb5834

**Comment by lyb5834** [comment]
应该支持的呀，我demo里也可以点击的啊，你是在swift项目中导入的吗？swift暂时还不支持






在2019年01月8日 11:52，ONG_J<notifications@github.com> 写道：

这样操作就没有...了 有没有办法让支持NSLineBreakByTruncatingTail @lyb5834

**Comment by JerryMR** [comment]
感谢回复！

OC项目，另外我在demo中测试，如果设置NSLineBreakByTruncatingTail点击只会触发首个字符的点击事件。

代码如下

`#import "ViewController.h"

#import "UILabel+YBAttributeTextTapAction.h"

@interface ViewController ()

@end

@implementation ViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view, typically from a nib.
    
    UILabel *label = [[UILabel alloc] initWithFrame:CGRectMake(20, 100, self.view.bounds.size.width - 40, self.view.bounds.size.height - 200)];
    label.textColor = [UIColor blackColor];
    label.numberOfLines = 3;
    label.userInteractionEnabled = YES;
    [self.view addSubview:label];
    
    NSMutableArray *tempTagList = [NSMutableArray new];
    
    NSMutableString *tempStr = [NSMutableString new];
    for (id tagModel in self.tagList) {
        if ([tagModel isKindOfClass:[NSString class]]) {
            NSString *tagListModel = tagModel;
            [tempStr appendFormat:@"%@ ",tagListModel];
            [tempTagList addObject:tagListModel];
        }
    }
    NSString *text = tempStr;
    NSMutableParagraphStyle *paragraphStyle = [[NSMutableParagraphStyle alloc] init];
    [paragraphStyle setLineSpacing:5.0f];        //设置行间距
    [paragraphStyle setLineBreakMode:NSLineBreakByTruncatingTail];
    [paragraphStyle setAlignment:NSTextAlignmentLeft];
    [paragraphStyle setLineBreakMode:NSLineBreakByCharWrapping];
    
    NSMutableAttributedString *attributedString = [[NSMutableAttributedString alloc] initWithString:text];
    [attributedString addAttribute:NSParagraphStyleAttributeName value:paragraphStyle range:NSMakeRange(0, [text length])];
    [attributedString addAttribute:NSFontAttributeName value:[UIFont systemFontOfSize:15] range:NSMakeRange(0, [text length])];
    
    label.attributedText = attributedString;
    
    if (tempTagList.count > 0) {
        [label yb_addAttributeTapActionWithStrings:[tempTagList copy] tapClicked:^(UILabel *label, NSString *string, NSRange range, NSInteger index) {
            NSLog(@"gakki 点击了---%@",string);
        }];
    }
}


- (NSArray *)tagList{
    return @[
             @" 去掉首页工具栏以下所有内容，banner也不保留，根据年龄切切换内容 ",
             @" 小时光4tab开发及嵌入 ",
             @" 数据过滤（我录的故事、播放历史、胎教） ",
             @" 音乐播放器（横竖屏播放） ",
             @" 孕育app内点击到小时光录制功能、播放付费内容、查看创作者首页、分享 ",
             @" 播放免费内容、更多内容页面跳转逻辑 ",
             @" 数据请求（筛除我录的故事、播放历史、胎教） ",
             @" 埋点（是否需要加） ",
             ];
}

@end
`

**Comment by lyb5834** [comment]
别设置这个属性可以吗？那是在文字排版放不下的时候省略符的位置啊！如果文字排版放不下，那我这个肯定计算不准，我的算法是建立在文字能全部显示的基础上的，毕竟UILabel要拿到系统的渲染文字规则很麻烦，暂时只能取巧了，文字放不下肯定不行的




在2019年01月8日 12:42，ONG_J<notifications@github.com> 写道：

感谢回复！

OC项目，另外我在demo中测试，如果设置NSLineBreakByTruncatingTail点击只会触发首个字符的点击事件。

代码如下

`#import "ViewController.h"

#import "UILabel+YBAttributeTextTapAction.h"

@interface ViewController ()

@EnD

@implementation ViewController

(void)viewDidLoad {
[super viewDidLoad];
// Do any additional setup after loading the view, typically from a nib.

UILabel *label = [[UILabel alloc] initWithFrame:CGRectMake(20, 100, self.view.bounds.size.width - 40, self.view.bounds.size.height - 200)];
label.textColor = [UIColor blackColor];
label.numberOfLines = 3;
label.userInteractionEnabled = YES;
[self.view addSubview:label];

NSMutableArray *tempTagList = [NSMutableArray new];

NSMutableString *tempStr = [NSMutableString new];
for (id tagModel in self.tagList) {
if ([tagModel isKindOfClass:[NSString class]]) {
NSString *tagListModel = tagModel;
[tempStr appendFormat:@"%@ ",tagListModel];
[tempTagList addObject:tagListModel];
}
}
NSString *text = tempStr;
NSMutableParagraphStyle *paragraphStyle = [[NSMutableParagraphStyle alloc] init];
[paragraphStyle setLineSpacing:5.0f]; //设置行间距
[paragraphStyle setLineBreakMode:NSLineBreakByTruncatingTail];
[paragraphStyle setAlignment:NSTextAlignmentLeft];
[paragraphStyle setLineBreakMode:NSLineBreakByCharWrapping];

NSMutableAttributedString *attributedString = [[NSMutableAttributedString alloc] initWithString:text];
[attributedString addAttribute:NSParagraphStyleAttributeName value:paragraphStyle range:NSMakeRange(0, [text length])];
[attributedString addAttribute:NSFontAttributeName value:[UIFont systemFontOfSize:15] range:NSMakeRange(0, [text length])];

label.attributedText = attributedString;

if (tempTagList.count > 0) {
[label yb_addAttributeTapActionWithStrings:[tempTagList copy] tapClicked:^(UILabel *label, NSString *string, NSRange range, NSInteger index) {
NSLog(@"gakki 点击了---%@",string);
}];
}
}

(NSArray *)tagList{
return @[
@" 去掉首页工具栏以下所有内容，banner也不保留，根据年龄切切换内容 ",
@" 小时光4tab开发及嵌入 ",
@" 数据过滤（我录的故事、播放历史、胎教） ",
@" 音乐播放器（横竖屏播放） ",
@" 孕育app内点击到小时光录制功能、播放付费内容、查看创作者首页、分享 ",
@" 播放免费内容、更多内容页面跳转逻辑 ",
@" 数据请求（筛除我录的故事、播放历史、胎教） ",
@" 埋点（是否需要加） ",
];
}

@EnD
`
