### ISSUE TITLE
cell中的label，点击不响应

### ISSUE THREAD

**Issue by LH-Liu** [lyb5834/YBAttributeTextTapAction#2]

**Comment by lyb5834** [comment]
你确定用的是我最新的代码吗？ 最新的代码应该没这问题啊！

**Comment by LH-Liu** [comment]
查出问题了，导致cell里label点击不响应，是因为label的attributedText包含表情NSTextAttachment属性，导致点击失效。。。

**Comment by Manzh** [comment]
这个coretext计算不支持NSTextAttachment导致，计算时替换一下就OK了
