### ISSUE TITLE
响应范围有点错误

### ISSUE THREAD

**Issue by lbininhbl** [lyb5834/YBAttributeTextTapAction#21]
我给一个默认的label设置了字符串@"abcdefg",然后调用添加点击的方法，参数为@[@"a", @"d"]的数组。
但是运行后的响应是a的能正确响应，d的响应位置跑到了b里去了。大概看了-yb_getTapFrameWithTouchPoint:result:方法，index的计算拿到的值在d的时候响应的值置值是不对应的。

**Comment by lbininhbl** [comment]
还有一个问题就是，假如我在点击响应的block里做了push一个viewcontroller的动作，-touchesEnded：withEvent：方法就不会被调用。这样就会导致我一点击字符串，就会直接push，然后pop出来之后字符串的点击效果就不会取消掉。

**Comment by lyb5834** [comment]
第一个问题，有的字符点击范围不对，这个应该是有的时候coretext的方法没有计算准确，因为大部分能点击的label都是自己重新渲染的，和我这个机制不一样，我准备等我空下来，全力解决这个问题，暂时你先尝试设置attributedString的时候设置全一点

第二个问题，麻烦您弄个pullrequest 我，我补全吧

**Comment by lbininhbl** [comment]
我也只是简单地把回调从-touchbegan:方法移到了-touchend:那边。我也只为了项目需要，暂时还没深究。上面只是我的初步想法，等我有空了可以看看怎么去优化吧。

**Comment by lyb5834** [comment]
您好，3.0.0最新版已更新，点击准确率大大提升，并且默认增加点击范围，欢迎使用
