### ISSUE TITLE
如果attributedText设置了段落style的话，点击范围计算的就不准确

### ISSUE THREAD

**Issue by luzsyn** [lyb5834/YBAttributeTextTapAction#25]
比如设置了段前间距，点击范围就会在文字的上方；

NSMutableParagraphStyle *bottomPara = [[NSMutableParagraphStyle alloc] init];
bottomPara.paragraphSpacingBefore = 30;
bottomPara.lineSpacing = 3;

**Comment by lyb5834** [comment]
你好，请使用3.0.0版本，已修复点击问题

**Comment by lyb5834** [comment]
你好，这个bug已经修复，感谢提醒






在2018年12月4日 18:05，AbelChan-AC<notifications@github.com> 写道：

3.0.0的点击还是有问题，加入了多个\n，设置了NSMutableParagraphStyle段落上下间距，点击错位比较严重哦
