### ISSUE TITLE
在 iOS 8.0 ~ iOS 8.4 之间的版本必现 crash

### ISSUE THREAD

**Issue by WaterSource** [lyb5834/YBAttributeTextTapAction#27]
如题

**Comment by lyb5834** [comment]
额，能定位到报错原因吗？我这边没有8.0的机器

**Comment by WaterSource** [comment]
堆栈信息如下: 
0 libobjc.A.dylib | objc_release + 20
-- | --
1 libobjc.A.dylib | (anonymous namespace)::AutoreleasePoolPage::pop(void*) + 564
2 CoreFoundation | _CFAutoreleasePoolPop + 28
3 Foundation | -[NSAutoreleasePool release] + 148
4 UIKit | -[UIApplication _run] + 588
5 UIKit | UIApplicationMain + 1488
6 DadaStaff | main (main.m:15)
7 libdyld.dylib | _start + 4

----------------------------------------
你可以用 Xcode 安装一个 8.0 ~ 8.4 之间的模拟器, demo 跑起来也是必现 crash 的

**Comment by lyb5834** [comment]
你好，闪退问题已经解决了，感谢您提供的宝贵意见

**Comment by WaterSource** [comment]
不客气.. 方便的话能说下思路吗, 不方便也没事的

**Comment by lyb5834** [comment]
闪退是因为我代码里写了dealloc 方法，iOS 8 貌似不支持category 里写这个方法，这方法我删掉了就OK了，本身写这方法就没意义，1年前的遗留代码，没有检查出来，不好意思

**Comment by WaterSource** [comment]
非常感谢, 感谢开源
