### ISSUE TITLE
iOS 8 下与 IQKeyboardManager 一起使用会崩溃

### ISSUE THREAD

**Issue by lbininhbl** [lyb5834/YBAttributeTextTapAction#29]
Podfile配置：

platform :ios, "8.0"
inhibit_all_warnings!

target ‘Test’ do

pod 'IQKeyboardManager' ,"6.2.0"
pod 'YBAttributeTextTapAction', '3.0.1'

end

iOS 8 以上没有问题，在 iOS 8 下会导致野指针，我注释掉 UILabel+YBAttributeTextTapAction.m 里的 - dealloc 方法后就不会有问题。

**Comment by lyb5834** [comment]
额，这个bug我已经发现了，早就修复了啊，你的版本旧了，现在pod的版本是 3.0.3 了

**Comment by lbininhbl** [comment]
> 额，这个bug我已经发现了，早就修复了啊，你的版本旧了，现在pod的版本是 3.0.3 了

噢噢，我pod search的时候看到是3.0.1。
我更新一下
