### ISSUE TITLE
swift中使用发现问题

### ISSUE THREAD

**Issue by oopyoung** [lyb5834/YBAttributeTextTapAction#3]
swift中调用yb_addAttributeTapActionWithStrings会crash掉

**Comment by lyb5834** [comment]
我正在编写swfit版，但是一个问题我暂时还没找到解决办法，就是把文字上下文转换成对象的时候，oc是可以强转的，swfit强转就报错，可能你在swfit中调用就会crash掉的原因，我正在找解决办法

**Comment by oopyoung** [comment]
感谢作者辛苦付出

发自我的 iPhone

**Comment by lyb5834** [comment]
不对啊，我试了一下，swfit可以正常调用的啊，没crash啊！你用的是最新版吗？
