### ISSUE TITLE
点击的响应位置根本就不对啊

### ISSUE THREAD

**Issue by xiaowangqinghui** [lyb5834/YBAttributeTextTapAction#30]
NSRange range = NSMakeRange(0, 4);
    NSRange range1 = NSMakeRange(7, 2);
    self.label.font = [UIFont systemFontOfSize:18];
    self.label.attributedText = hintString;
//    [self.label yb_addAttributeTapActionWithStrings:@[@"这是一个",@"注意"] delegate:self];
    [self.label yb_addAttributeTapActionWithRanges:@[NSStringFromRange(range),NSStringFromRange(range1)] tapClicked:^(UILabel *label, NSString *string, NSRange range, NSInteger index) {
        if ([string isEqualToString:@"这是一个"]) {
            NSLog(@"-----typefdssgs");
        }else{
            NSLog(@"-----这是一个");
        }
    }];
//    [self.label yb_addAttributeTapActionWithStrings:@[@"这是一个",@"注意"] tapClicked:^(UILabel *label, NSString *string, NSRange range, NSInteger index) {
//        if ([string isEqualToString:@"这是一个"]) {
//            NSLog(@"-----typefdssgs");
//        }else{
//            NSLog(@"-----这是一个");
//        }

**Comment by lyb5834** [comment]
字体设置不要这样赋值，`NSFontAttributeName : [UIFont systemFontOfSize:18]`用这种

**Comment by xiaowangqinghui** [comment]
不设置字体也不行 用富文本设置居中什么的也不行啊

**Comment by xiaowangqinghui** [comment]
UILabel *protLab = [[UILabel alloc] initWithFrame:CGRectMake(0, bottomBgView.height-45, TheWidth, 20)];
    NSString *text = @"登录即代表同意《恋爱话术服务协议》";
    NSMutableAttributedString *hintString = [[NSMutableAttributedString alloc]initWithString:text];
    NSMutableParagraphStyle *sty = [[NSMutableParagraphStyle alloc] init];
    sty.alignment = NSTextAlignmentCenter;
    [hintString addAttribute:NSParagraphStyleAttributeName value:sty range:NSMakeRange(0, text.length)];
    NSRange rang2= [text rangeOfString:@"《恋爱话术服务协议》"];
    NSRange range= [text rangeOfString:@"登"];
//    [hintString addAttribute:NSForegroundColorAttributeName value:[UIColor greenColor] range:range];
//    [hintString addAttribute:NSForegroundColorAttributeName value:[UIColor greenColor] range:range2];
    protLab.attributedText = hintString;
//    [protLab yb_addAttributeTapActionWithStrings:@[@"登",@"《恋爱话术服务协议》"] delegate:self];
    [protLab yb_addAttributeTapActionWithRanges:@[NSStringFromRange(range),NSStringFromRange(rang2)] delegate:self];
    protLab.enabledTapEffect = YES;
    [bottomBgView addSubview:protLab];
到底哪里错了呢

**Comment by lyb5834** [comment]
你确定你用富文本的方式设置字体了吗？你试试我的demo点击准不准或者你做个demo发给我，我看看原因

**Comment by xiaowangqinghui** [comment]
demo发你邮箱了啊

**Comment by xiaowangqinghui** [comment]
[TEsttte.zip](https://github.com/lyb5834/YBAttributeTextTapAction/files/2965571/TEsttte.zip)
看

**Comment by lyb5834** [comment]
加一句 [hintString addAttribute:NSFontAttributeNamevalue:[UIFontsystemFontOfSize:18] range:NSMakeRange(0, text.length)]; 就OKle 




在2019年03月14日 17:05，xiaowangqinghui<notifications@github.com> 写道：

TEsttte.zip
看

**Comment by xiaowangqinghui** [comment]
一定要设置字体吗  我看别人在xib设置的字体也是正常的啊
用默认字体不行？
//文本点击
        NSMutableAttributedString * hintString = [[NSMutableAttributedString alloc]initWithString:@"注册代表你已同意注册协议和隐私协议"];
        NSRange range= [[hintString string]rangeOfString:@"注册协议"];
           NSRange range2= [[hintString string]rangeOfString:@"隐私协议"];
        [hintString addAttribute:NSForegroundColorAttributeName value:ATGreenColor range:range];
          [hintString addAttribute:NSForegroundColorAttributeName value:ATGreenColor range:range2];
        _registLable.attributedText =hintString ;
        [_registLable yb_addAttributeTapActionWithStrings:@[@"注册协议",@"隐私协议"] delegate:self];
        _registLable.enabledTapEffect = NO;

**Comment by lyb5834** [comment]
必须要加的，我的计算是建立在label.AttributedText 上的，你没设置字体我就获取不到，计算更是不准的




在2019年03月14日 17:13，xiaowangqinghui<notifications@github.com> 写道：

一定要设置字体吗 我看别人在xib设置的字体也是正常的啊
用默认字体不行？
//文本点击
NSMutableAttributedString * hintString = [[NSMutableAttributedString alloc]initWithString:@"注册代表你已同意注册协议和隐私协议"];
NSRange range= [[hintString string]rangeOfString:@"注册协议"];
NSRange range2= [[hintString string]rangeOfString:@"隐私协议"];
[hintString addAttribute:NSForegroundColorAttributeName value:ATGreenColor range:range];
[hintString addAttribute:NSForegroundColorAttributeName value:ATGreenColor range:range2];
_registLable.attributedText =hintString ;
[_registLable yb_addAttributeTapActionWithStrings:@[@"注册协议",@"隐私协议"] delegate:self];
_registLable.enabledTapEffect = NO;
