### ISSUE TITLE
添加NSTextAttachment的部分不可以点击

### ISSUE THREAD

**Issue by luzsyn** [lyb5834/YBAttributeTextTapAction#33]
NSMutableAttributedString中添加了NSTextAttachment图片附件，图片附件部分不可以点击，有什么办法解决吗？

**Comment by lyb5834** [comment]
添加UIbutton附件吧。。。

**Comment by luzsyn** [comment]
您的意思是把UILabel换成UIButton显示？可是需求是只想在文字末尾添加图片，而且是图片可以点击，文字不可以点击

**Comment by lyb5834** [comment]
添加按钮附件，按钮本身就是可以加点击事件的




在2019年04月10日 11:23，刘志新 写道：

您的意思是把UILabel换成UIButton显示？可是需求是只想在文字末尾添加图片，而且是图片可以点击，文字不可以点击

**Comment by luzsyn** [comment]
请问如何添加按钮附件？貌似NSTextAttachment只能添加图片吧？

**Comment by lyb5834** [comment]
好吧，我弄错了，不能添加别的附件的，我这个框架是轻量级的，所以只支持文字点击，不支持图片点击的，抱歉，推荐你大型图文混排使用YYText吧
