### ISSUE TITLE
swift 项目使用本框架，点击左边，响应的是右边，点击右边没有效果。

### ISSUE THREAD

**Issue by csc-EricWu** [lyb5834/YBAttributeTextTapAction#37]
![image](https://user-images.githubusercontent.com/13517061/61165932-872c2380-a559-11e9-891b-b1a67c5781ec.png)

```
  let normalStyle = [NSAttributedString.Key.font: UIFont.pingFangRegular(ofSize: 12),
                           NSAttributedString.Key.foregroundColor: CRRGBA_X(rgb: 0x91949B)]
  let linkStyle = [NSAttributedString.Key.font: UIFont.pingFangRegular(ofSize: 12),
                         NSAttributedString.Key.foregroundColor: CRRGBA_X(rgb: 0x3885F6)]
  let privacyAttr = NSMutableAttributedString(string: "登录/注册即表示您同意", attributes: normalStyle)
 let userPrivacy = "《用户注册协议》"

 privacyAttr.append(NSAttributedString(string: userPrivacy, attributes: linkStyle))
 lblPrivacy.attributedText = privacyAttr
 weak var __self = self
 lblPrivacy.yb_addAttributeTapAction(with: [userPrivacy]) { _, _, _, _ in
        __self?.showPrivacyController()
 }
```

**Comment by lyb5834** [comment]
我自己在swift项目中没问题呀！




在2019年07月13日 10:35，Eric Wu 写道：

  let normalStyle = [NSAttributedString.Key.font: UIFont.pingFangRegular(ofSize: 12),

                           NSAttributedString.Key.foregroundColor: CRRGBA_X(rgb: 0x91949B)]

  let linkStyle = [NSAttributedString.Key.font: UIFont.pingFangRegular(ofSize: 12),

                         NSAttributedString.Key.foregroundColor: CRRGBA_X(rgb: 0x3885F6)]

  let privacyAttr = NSMutableAttributedString(string: "登录/注册即表示您同意", attributes: normalStyle)

 let userPrivacy = "《用户注册协议》"



 privacyAttr.append(NSAttributedString(string: userPrivacy, attributes: linkStyle))

 lblPrivacy.attributedText = privacyAttr

 weak var __self = self

 lblPrivacy.yb_addAttributeTapAction(with: [userPrivacy]) { _, _, _, _ in

        __self?.showPrivacyController()

 }

**Comment by csc-EricWu** [comment]
我写了个demo 在模拟器iPhone X 系统版本为12.2 上确实有，怎么把demo 给你？

**Comment by lyb5834** [comment]
lyb5834@126.com 发我邮箱吧，我星期一才能看




在2019年07月13日 11:02，Eric Wu 写道：

我写了个demo 在模拟器iPhone X 系统版本为12.2 上确实有，怎么把demo 给你？

**Comment by csc-EricWu** [comment]
好的。

**Comment by csc-EricWu** [comment]
有重现吗？大佬

**Comment by lyb5834** [comment]
我不是把解决方案的demo发你邮箱了吗，

**Comment by csc-EricWu** [comment]
感谢，按照大佬提示，解决了问题。
