### ISSUE TITLE
label上增加点击手势后，文本高亮点击事件无效

### ISSUE THREAD

**Issue by itzhaolei** [lyb5834/YBAttributeTextTapAction#40]
我下载了最新的Demo，运行后，点击文本高亮部分，控制台一直输出的是点击手势事件。希望尽快修复这个问题。

**Comment by lyb5834** [comment]
点击事件是有效的，只不过手势和点击事件会同时触发而已，你仔细看demo

**Comment by itzhaolei** [comment]
Demo中【label上加手势】，我反复通过控制台和断点调试验证，代理方法和block是无效事件，只有tap和cell的didSelectRowAtIndexPath函数被调用。我这边的项目想使用您的这个三方库，但是项目要求点击普通文本弹出评论框，需要tap事件和高亮文字事件都能得到相应。您再帮忙看下呢，我可以提供当前的Demo，我QQ号1824964911。

**Comment by lyb5834** [comment]
搞不懂，我也是用的项目里的demo，手势和文字点击事件都正常触发啊

**Comment by itzhaolei** [comment]
如上述问题，当给label增加点击手势后，label会由【轻点】高亮文字，变为了【按压】高亮文字，才能触发高亮文字的点击事件。您的这个库是存在这个问题的，这也是我为什么没有触发事件，因为我一直在【轻点】高亮文字。

**Comment by lyb5834** [comment]
可能是touch事件和tap手势的问题吧，为什么非要加手势呢？我的那个传入的数组，完全可以分段触发不同的事件啊

**Comment by itzhaolei** [comment]
可能是我没点击准的问题，轻点高亮文字居然也触发了（可能点击需要较高的精确度）。打扰你了，不好意思哈。
