### ISSUE TITLE
通过storyboard创建的label点击的响应位置出现了偏移

### ISSUE THREAD

**Issue by 1174784586** [lyb5834/YBAttributeTextTapAction#8]
用纯代码创建的label能准确无误的在指定位置响应点击事件，但是在storyboard里面在同样的位置创建同样的label，响应点击事件的位置与指定的string位置出现了很大的偏差

**Comment by 1174784586** [comment]
经过多次测试发现，如果是通过xib或者storyboard画的label，必须要在设置富文本的时候加上[attributedString2 addAttribute:NSFontAttributeName value:[UIFont systemFontOfSize:15] range:NSMakeRange(0, self.testLabel.text.length)];  这样一句代码去设置label的UIFont属性才可以避免点击的时候出现位置偏差的问题

**Comment by lyb5834** [comment]
试试新版本，demo我就是用xib建的label，点击很精准
