### ISSUE TITLE
重大bug！设定的文字前半部分能点击，后边的不能点击。

### ISSUE THREAD

**Issue by Allensa** [lyb5834/YBAttributeTextTapAction#9]
重大bug！设定的文字前半部分能点击，后边的不能点击。

**Comment by AllenMon** [comment]
例如  名字：小明    ，【名字：】设定不能点，【小明】能点,但现在[小]能点[明]不能点

**Comment by lyb5834** [comment]
不应该啊，我没发现过类似的情况，方便发个demo到我邮箱吗？lyb5834@126.com

**Comment by AllenMon** [comment]
NSString *telNumber = @"110123456789";
    NSString *telString = [NSString stringWithFormat:@"门店电话：%@", telNumber];
    NSRange telRange = [telString rangeOfString:telNumber];
    NSMutableAttributedString *text = [[NSMutableAttributedString alloc] initWithString:telString];
    [text addAttribute:NSUnderlineStyleAttributeName value:@(NSUnderlineStyleSingle) range:telRange];
    [self.telephoneLabel setAttributedText:text];
    WeakObject(self)
    [self.telephoneLabel yb_addAttributeTapActionWithStrings:@[telNumber] tapClicked:^(NSString *string, NSRange range, NSInteger index) {
        StrongObject(self)
        [self telephoneButtonTouched];
    }];


这段富文本，点最后的789没反应，你可以试试。

**Comment by AllenMon** [comment]
NSString *telNumber = @"110123456789";
NSString *telString = [NSString stringWithFormat:@"门店电话：%@", telNumber];
NSRange telRange = [telString rangeOfString:telNumber];
NSMutableAttributedString *text = [[NSMutableAttributedString alloc] initWithString:telString];
[text addAttribute:NSUnderlineStyleAttributeName value:@(NSUnderlineStyleSingle) range:telRange];
[self.telephoneLabel setAttributedText:text];
WeakObject(self)
[self.telephoneLabel yb_addAttributeTapActionWithStrings:@[telNumber] tapClicked:^(NSString *string, NSRange range, NSInteger index) {
StrongObject(self)
[self telephoneButtonTouched];
}];

这段富文本，点最后的789没反应，你可以试试。

**Comment by lyb5834** [comment]
你试试设置下attributeFont就是`[text addAttribute:NSFontAttributeName value:[UIFont systemFontOfSize:15] range:NSMakeRange(0, text.length)]`应该就可以了

**Comment by AllenMon** [comment]
可以了，但我已经设置国普通文本的文字颜色,显示也正常,富文本显示也正常,就没设置富文本的.

不知产生这一问题的原因是什么,能否修复?

最后提个建议,能否传Range来确定点击文字?

**Comment by lyb5834** [comment]
你意思是点击变灰吗？那是点击效果，如果不要可以关闭，你的建议我会考虑，到下版再添上吧

**Comment by AllenMar** [comment]
Good job!  不是点击效果,就是没设置字体为什么会产生这一问题
